### PR TITLE
writeRows current behavior is actually append

### PR DESCRIPTION
**Pull request by jonnyjonjon**
making default and throwing exception for other writeDispositions

### CODE REVIEW

**Comment by jto** [comment]
I'm not sure I understand what the PR is meant to do. The current behaviour in Scio is consistent with beam's bigquery client (see: https://beam.apache.org/releases/javadoc/2.8.0/org/apache/beam/sdk/io/gcp/bigquery/BigQueryIO.Write.WriteDisposition.html#WRITE_EMPTY). If for some reason it does not work, I think the bug should be reported and fixed upstream.

**Comment by jonnyjonjon** [comment]
Thanks for the quick reply. Yes, I understand what WRITE_EMPTY is supposed to do. You will notice, though, that in TableOps.scala, Scio drops the writeDisposition parameter entirely in the writeRows method I edited - it does not even pass it to beam.

Under the hood, it's using a beam streaming insert method that only appends (which actually caused a rather nasty bug for us).

The user doesn't get alerted that their disposition parameter is being ignored, nor is there any indication about how the method actually behaves.

This PR isn't meant to change the behavior, just alert a user that WRITE_TRUNCATE will not overwrite, and WRITE_EMPTY will not throw an error if the destination is not empty.

**Comment by regadas** [comment]
Issue #1511

**Comment by jonnyjonjon** [comment]
Great! Thanks for creating the issue. I understand that you'd rather have write dispositions functional, but wouldn't this exception help prevent unexpected behavior for users in the meantime?

**Comment by regadas** [comment]
Closing via #1541

**Pull request closed without merging**
