### PR TITLE
Monkey-patch BigtableIO for 0.9.5.1 #495

### PR DESCRIPTION
**Pull request by andrewsmartin**

### CODE REVIEW

**Comment by nevillelyh** [comment]
Rename `BigtableIO` to `PatchedBigtableIO` in case any class loading issue?
Also does this work with the test job?

**Comment by andrewsmartin** [comment]
Decided against renaming -> `PatchedBigqueryIO` because this class passes `this` references to other API calls which expect `BigqueryIO`.

**Comment by nevillelyh** [comment]
:+1:

**Comment by regadas** [comment]
👍

**Pull request merged**
