### PR TITLE
Add scalafix rule to rename join names

### PR DESCRIPTION
**Pull request by syodage**
Fixes https://github.com/spotify/scio/issues/2448

Add scalafix 0.8.0 migration rules to update join API changes introduced by https://github.com/spotify/scio/pull/2444

### CODE REVIEW

**Comment by nevillelyh** [comment]
Also breaking `scalafmt`?

**Comment by syodage** [comment]
@nevillelyh scalafmt works ok.

**Comment by nevillelyh** [comment]
Looks like it's breaking because of the scalatest change `/home/circleci/scio/scio-test/src/it/scala/com/spotify/scio/bigquery/TypedBigQueryIT.scala:75:49: not found: type BeforeAndAfterAll`. Rebase on master?

**Comment by jto** [comment]
Can we also keep the old methods and deprecate them please ?

**Pull request merged**
