### PR TITLE
Idea 1 for named transforms

### PR DESCRIPTION
**Pull request by andrewsmartin**
WIP please don't merge. @ElPicador @nevillelyh Here's one idea for implementing named transforms. What do you think? If we're all on board with this we can try to come up with a sexier DSL.

### CODE REVIEW

**Comment by andrewsmartin** [comment]
@ravwojdyla also

**Comment by ElPicador** [comment]
My thoughts:

- I'm not a big fan of weird method names (aka not words)
- I like the fact that it doesn't breaks the "flow" of the code

**Comment by ElPicador** [comment]
But whatever the final decision, thanks for implementing it 👍

**Comment by andrewsmartin** [comment]
@ElPicador So if we were to instead just make it simple like

`.map(...).withName("name")`

would you prefer this over the other solution? We can also just have the regular `SCollection` be lazy by default so it can be built in to the normal API.

**Comment by ElPicador** [comment]
@andrewsmartin I think it's more readable for non scala experts

**Comment by andrewsmartin** [comment]
@ElPicador cool, I can do that then. One last thing, I could also do something similar in the other PR, i.e. `.withName("name").map(...)`, and in either case the `.withName` will always be optional. From a readability standpoint, which would you rather have?

I also did play with an implicit `apply(name: String)` in this PR, so it would look like this: `.filter(...)("name")`, and I think this would have honestly been the best approach, but unfortunately it doesn't work for any transform like `map` which has an implicit class tag parameter. To the best of my knowledge there isn't any way around that but I think would be the best approach if it is somehow possible. Otherwise I will stick with this.

**Comment by ElPicador** [comment]
I would prefer `.map(...).withName("name")` but I don't have any good reason 😄

**Comment by andrewsmartin** [comment]
Cool, I think that's more readable as well.

**Comment by nevillelyh** [comment]
I think we've narrowed it down to `.withName("name").flatMap(fn)` vs `.flatMap(fn).withName("name")` right? Between these 2 I prefer the former because it's clearer (name the following transform instead of default behavior) and probably easier to implement.

**Comment by andrewsmartin** [comment]
Let's go with that then for now - if it turns out later there's a good reason for switching and using lazily-applied transforms instead, we can always revisit. For now #357 will work.

**Pull request closed without merging**
