### PR TITLE
Add helper to run jobs with managed ScioContext.

### PR DESCRIPTION
**Pull request by andrewsmartin**
Not sure about the `submitJob` name, open to suggestions. `runWithContext` seems better but we're also using that for tests.

### CODE REVIEW

**Comment by nevillelyh** [comment]
What's the use case for this?

**Comment by andrewsmartin** [comment]
Forgetting to call `sc.close()` has been a bit of a gotcha sometimes. This is just an optional, alternative style to write jobs without needing to explicitly open and close a context. It's not much code so I feel it's worth having.

**Comment by nevillelyh** [comment]
But won't work with a lot of other things we have like `ScioResult` and metrics. In the end probably adds more confusion than problems it fixes?

**Comment by andrewsmartin** [comment]
The helper returns the `ScioResult` so the metrics and all that should work properly. But like we discussed offline `JobTest` would fail if the context is not closed, so maybe this isn't useful outside of experimental / pre-production work. Up to you whether or not it's worth keeping.

**Comment by nevillelyh** [comment]
Let's close for now. It'll be harder to tell people to switch to this than just not forget `sc.close()` :)

**Pull request closed without merging**
