### PR TITLE
Add ValueProvider support to TextIO

### PR DESCRIPTION
**Pull request by regadas**
Related to #3061

### CODE REVIEW

**Comment by jto** [comment]
Do we have any status from Google about the status of `ValueProvider` ? 
I'd like to be sure they won't deprecate them soon-ish before we spend time adding support.

**Comment by regadas** [comment]
It's a good question! from one of the conversations with them `Traditional Templates` were not being deprecated in favour of `Flex Templates` but simply providing a different templating approach. I think that still stands, but we should probably follow up with them.

**Comment by nevillelyh** [comment]
To do this properly, we'll have to do this for all IOs right?

**Comment by jto** [comment]
Can we merge this PR @regadas ?

**Review by regadas — COMMENTED** [review]
We believe that *Flex Templates* offers more flexibility and Google seems to be on the same page. For that reason we will not add *Traditional Template* support.

**Pull request closed without merging**
