### PR TITLE
Separate io directory for IOs

### PR DESCRIPTION
**Pull request by ravwojdyla**

### CODE REVIEW

**Comment by nevillelyh** [comment]
Maybe hold on to this for now. Avro, BigQuery, TF, etc. are kind of `IO` but include some other logic, not sure how to group them. Also not sure the stuff in `scio-extra` right now.
Maybe save for later when we decide to split up `scio-extra`?

**Comment by ravwojdyla** [comment]
How about we gradually split this, the ones moved in are obvious IOs. And once we figure out how to split BQ/Avro/TF we can move it around. The `scio-extra`, probably does not make sense to split just now yet, but once it's time, there would probably be another directory `extra` with further submodules?

**Comment by nevillelyh** [comment]
This is outdated. Now I think more about it, doesn't seem to add any benefit and it might actually cause more confusion, e.g. project name and path mismatch. Close for now?

**Comment by nevillelyh** [comment]
Gonna close for now.

**Pull request closed without merging**
