### PR TITLE
remove unused coverage steps

### PR DESCRIPTION
**Pull request by nevillelyh**

### CODE REVIEW

**Comment by andrewsmartin** [comment]
The point of including it there was to keep the settings the same so they could be cached. If we remove it but then keep it in the test step, it causes a re-application of settings and forces the resolver to do everything again.

**Comment by nevillelyh** [comment]
Do you mean cache for Ivy artifacts? `coverage` is from a plugin and its artifacts are downloaded when SBT starts and shouldn't matter whether we run the step or not? On the other hand having `coverage` on may slow down some tests? May doesn't matter after all since neither `compile` nor `assembly` runs any test.

**Comment by andrewsmartin** [comment]
It's for the sbt resolution cache (not ivy cache). https://github.com/spotify/scio/pull/484#issue-214212473

**Comment by nevillelyh** [comment]
:+1:

**Pull request closed without merging**
