### PR TITLE
Added methods for reading multiple hdfs files

### PR DESCRIPTION
**Pull request by andrewsmartin**

### CODE REVIEW

**Comment by nevillelyh** [comment]
Do we really need this? It's pretty easy to `sc.hdfsAvroFile` and `unionAll` later.
Plus this will make the HDFS Avro API inconsistent with other file based sources.

**Comment by andrewsmartin** [comment]
Yeah, not really much boilerplate to begin with I guess. Was thinking it would be nice to support out of the box directly from the cmd line args but I agree -- consistency probably more important

**Comment by andrewsmartin** [comment]
@nevillelyh @ravwojdyla Revisiting this - what if we just use varargs and always unionAll (even if just one input)?

**Comment by nevillelyh** [comment]
Varargs only works if it's the last arg and there're no other args with default value. So doing it will still make this API inconsistent with everything else.

**Pull request closed without merging**
