### PR TITLE
deprecate at 0.12.0

### PR DESCRIPTION
**Pull request by brucearctor**

### CODE REVIEW

**Comment by brucearctor** [comment]
Addressing: https://github.com/spotify/scio/issues/4341

**Comment by brucearctor** [comment]
@RustedBones -- updating timeline/messaging in code, in case 0.12.0 is not the next release.

**Comment by RustedBones** [comment]
Thanks for the PR @brucearctor.
We're already preparing the 0.12.0 release. Except if we find some bugs, we are not going to have another 0.11.x release.
I think you can already cleanup the deprecated code, without changing the message

**Comment by brucearctor** [comment]
I jumped on something else -- not likely to relook at this for probably at least a week.

**Pull request closed without merging**
