### PR TITLE
Adding onJobStart hook to ScioContext

### PR DESCRIPTION
**Pull request by d4nilos**
We have a use case for something similar to https://github.com/spotify/scio/issues/1848 but our handler needs the ClosedScioContext. 

The reason is that we need to get the Dataflow Job ID at the start of a job, even if --blocking is used.

Thanks and have a nice day

### CODE REVIEW

**Comment by gizem969** [comment]
Hi @regadas ,

We are using the [bigtable autoscaler](https://github.com/spotify/bigtable-autoscaler) to manage our bigtable clusters. If we use the utility functions in `scio-bigtable` to manually scale up before the pipeline, it clashes with the autoscaler, so instead we have a separate system that monitors the pipelines running on our clusters and informs the autoscaler as described [here](https://github.com/spotify/bigtable-autoscaler#does-it-handle-sudden-load-spikes-for-instance-dataflow-jobs-readingwriting-batch-data).

What we want to do is, inform our system that a pipeline is about to start, sleep, inform the system that the pipeline has been submitted with `dataflow jobid`. Afterwards our system will monitor its status from the Dataflow API and make necessary calls to the autoscaler.
In essense, what we need is the ability to execute some piece of code as soon as we get the job id from dataflow. We don't want to wait for the pipeline to finish. Theoretically, this could be achievable right after calling `close()`, however some pipelines configure `isBlocking`( https://github.com/spotify/scio/blob/master/scio-core/src/main/scala/com/spotify/scio/ScioContext.scala#L574 ), so it doesn't work.

**Comment by regadas** [comment]
Hi @gizem969 Thanks for the explanation! 

> Theoretically, this could be achievable right after calling close(), however some pipelines configure isBlocking

Yes, i think this is the main issue and it should be addressed! Given the new semantic brought by `ClosedScioContext` this option does not make that much sense and it should be removed. With its removal there shouldn't be a need for hooks.

**Comment by gizem969** [comment]
Hi @regadas , yes if it can be ensured that `close()` is always non-blocking, then it'd work. One advantage of having hooks might be that for cases like these, where external scio plug-ins change the state of a resource or do anything else that needs to be reverted/updated depending on the state of the pipeline, they can simply add these actions as callbacks rather than relying on clients to explicitly adding those steps to their pipelines.

**Comment by Bj0rnen** [comment]
@gizem969 I don't know the Scala syntax, but you can most likely write a higher order function that "wraps around" the pipeline code (sort of like a try-with-resources block in Java). So something like this:
```scala
val sc = ...
val closedContext = runJobWithExtraBigtableNodes(
    instanceId = "foo",
    clusterId = "c1",
    extraNodes = 25,
    waitTimeMinutes = 20,
    pipeline = () => {
  // 20 minutes will pass before this block of code runs,
  // so that Bigtable has time to scale up.

  // Do stuff with sc...
  sc.close()  // The ClosedScioContext is picked up by runJobWithExtraBigtableNodes,
              // which can find out the dataflow jobid.
})

// The ClosedScioContext is also passed through runJobWithExtraBigtableNodes,
// and can be used for further steps.
closedContext.waitUntilDone()
```
The type of `runJobWithExtraBigtableNodes` in this example is (sorry, Haskell syntax)
```haskell
String -> String -> Int -> Int -> (() -> ClosedScioContext) -> ClosedScioContext
```

**Comment by regadas** [comment]
Hi @d4nilos @gizem969 so we are deprecating `.close()` and with it the `blocking` behavior in favor of:

 https://github.com/spotify/scio/blob/ca8d49c16adf30ce41e9d27e6729d4ee9422e360/scio-core/src/main/scala/com/spotify/scio/ScioContext.scala#L637

This should effectively remove the need for these kinda of hooks.

**Pull request closed without merging**
