### PR TITLE
Use MonoidAggregator when available, fix #3050

### LINKED ISSUE #3050: Support `MonoidAggregator`
Currently `SCollection#aggregate*` takes `Aggregator[A, B, C]` and does `.map(a.prepare).sum(a.semigroup).present(c)` under the hood. This might fail for empty windows.

### PR DESCRIPTION
**Pull request by nevillelyh**

### CODE REVIEW

**Comment by nevillelyh** [comment]
Yeah don't have strong opinion. I looked at Scalding and `MonoidAggregator` wasn't used anywhere in the code base. I wonder if majority of semigroups are already monoids and therefore `MonoidAggregator` should be the default?

**Comment by regadas** [comment]
hm, I'm guessing they just don't leverage them 🤷 There are some `Aggregator` that are not `monoid`'s i.e `min/max` so i think supporting both is good! I lean however to have separate methods though.

**Comment by nevillelyh** [comment]
Let me play around it first. `MonoidAggregator` sounds like an impl detail (although it's not) and might be confusing to users since it's not surfaced anywhere else in Algebird/Scalding docs.

**Comment by nevillelyh** [comment]
Switched to overloading approach. Seems to work.

**Pull request merged**
