### PR TITLE
Support for AvroType macros

### PR DESCRIPTION
**Pull request by i-maravic**
Added support for:

@AvroType.fromSchema -
  generates case classes and their companion objects from Avro schema json
@AvroType.fromPath -
  generates case classes and their companion objects from GCS path. Globs are supported.
@AvroType.toSchema -
  generates Avro schema and compantion object from a case class.

A convenience function is provided in ScioContext to read Avro files to generated case classes:

ScioContext.typedAvroFile

A convenince function is provided to SCollection to write Avro files from generated case classes:

SCollection.saveAsTypedAvroFile

### CODE REVIEW

**Comment by ravwojdyla** [comment]
@i-maravic could you give a short explanation of what problem you are trying to solve?

**Comment by i-maravic** [comment]
@ravwojdla my goal is to be able to generate case classes based on Schema in a GCS folder, similar to how BQType does it for BQ tables.

**Comment by nevillelyh** [comment]
Great stuff. LGTM except some minor comments but I can merge and fix later.

**Comment by i-maravic** [comment]
@nevillelyh Let me fix the docs and comments and I (or you) can merge this later today.

**Pull request merged**
