### PR TITLE
Use beam-runners-flink-1.10 when using BEAM_USERS

### PR DESCRIPTION
**Pull request by regadas**

### CODE REVIEW

**Comment by nevillelyh** [comment]
2.24.0 will be released soon with 1.11 runner, should we wait?

**Comment by regadas** [comment]
this is making it consistent with what we have https://github.com/spotify/scio/blob/3503b0c3d2db718c474f9457ad40ec5003ffe7b9/build.sbt#L487-L492

I thought it would be only be on `2.25.0` if it's early awesome

**Comment by regadas** [comment]
actually let me change this since it might happen in the future

**Review by regadas — COMMENTED** [review]
@nevillelyh gonna merge this, just because we already have `1.10` on scio-core

**Pull request merged**
