### PR TITLE
add check for test IO outside of JobTest

### PR DESCRIPTION
**Pull request by nevillelyh**

### CODE REVIEW

**Comment by nevillelyh** [comment]
@andrewsmartin @richwhitjr take a look?

**Comment by andrewsmartin** [comment]
+1 Nice, although is the error message clear enough for `.materialize`? I know it's output under the hood but might not be clear to the user.

**Comment by nevillelyh** [comment]
It's hard to be more specific coz `saveAs*` are all outputs and can't easily tell from which.

**Comment by andrewsmartin** [comment]
Yeah - alright, I think it's fine then

**Pull request merged**
