### PR TITLE
Have deterministic names for transformations

### PR DESCRIPTION
**Pull request by ElPicador**
Ref #163

Sorry for the delay, I had some health issues.

WDYT of it?

### CODE REVIEW

**Comment by nevillelyh** [comment]
Can you add a flag so this is only turned on in streaming mode? Maybe an `object CallSites` and a `var` inside set by `ScioContext` based on `PipelineOptions`. That way you can also keep the `getCurrent` method name.

I'd also keep the file name part since it's even less likely to change than method name, e.g. one replace `map` with `flatMap`.

And more importantly, have you verified that this works?

**Comment by ElPicador** [comment]
Why only enable this on streaming mode?

I don't really agree on the file name part. You can split your pipeline in multiple files without changing it. So adding the file name prevent some (simple) refactoring.

I've tested it locally. But you are right, I'll test it with one of our pipeline

**Comment by nevillelyh** [comment]
It's still nice to have filename and line number, especially in complex pipelines with many similar transforms. So I prefer to not change the behavior for the large number of existing batch users :)

Don't have a strong opinion on filename in streaming, but it can be confusing if you have transforms of the same name spread across multiple files.

**Comment by ElPicador** [comment]
This won't work on the long run, closing it and continuing discussion on the issue #163

**Pull request closed without merging**
