### PR TITLE
Make scio compilation faster

### PR DESCRIPTION
**Pull request by jto**

### CODE REVIEW

**Comment by regadas** [comment]
Hi @jto is this ready for review?

**Comment by jto** [comment]
@regadas yes

**Comment by nevillelyh** [comment]
Can we hold off on the shapeless-scalacheck related changes?

I got the magnolia-based one to work fairly well but want to clean up some stuff before making a release.
https://github.com/nevillelyh/magnolia-data/blob/master/scalacheck/src/main/scala/magnolia/scalacheck/semiauto/ArbitraryDerivation.scala

**Comment by nevillelyh** [comment]
#2346 supercedes this. Can we rebase this to keep only the sbt changes?

**Comment by nevillelyh** [comment]
@jto ping. Should we close this or maybe split out the non-shapeless changes into another PR?

**Pull request closed without merging**
