### PR TITLE
Add checkinit to scalac opts

### PR DESCRIPTION
**Pull request by ravwojdyla**

### CODE REVIEW

**Comment by nevillelyh** [comment]
Is there gonna be a performance hit? What's the main reason for this?

**Comment by ravwojdyla** [comment]
Prevention. Performance hit - not that I'm aware of.

**Comment by ravwojdyla** [comment]
For doc: https://groups.google.com/forum/#!topic/scala-internals/twuNGENFOL8

**Comment by ravwojdyla** [comment]
Closing this for now, and will open an issue.

**Pull request closed without merging**
