### PR TITLE
Support ByteChannelFactory in TextIO

### PR DESCRIPTION
**Pull request by ravwojdyla**
This apart from other stuff enables compression on output of text io.

### CODE REVIEW

**Comment by ravwojdyla** [comment]
If good with you, will add test.

**Comment by nevillelyh** [comment]
Not sure if we should expose WBC in API though. Maybe not so straightforward to use for those who don't know the underlying IO module?

**Comment by nevillelyh** [comment]
Either wrap the impls in an enum/case object, or alias the Java type?

**Comment by ravwojdyla** [comment]
@nevillelyh what do you think about this?

**Comment by ravwojdyla** [comment]
Example of usage would be:

```
import com.spotify.scio.io.compression._
sc.parallelize(1 to 100).saveAsTextFile("/tmp/t5", numShards=1, compression=Compression.GZIP)
```

to save a single `GZIP`ed file.

**Comment by nevillelyh** [comment]
LGTM. What do you think about other non user facing classes in io package? Remove/hide to make it easier to import io._?

**Comment by ravwojdyla** [comment]
@nevillelyh i guess out of the scope of this PR, but +1 to hiding everything that users doesn't need to see.

**Comment by ravwojdyla** [comment]
@nevillelyh added tests, also updated to use `Compression` to align with `textFile` method.

**Pull request merged**
