### PR TITLE
[wip] Add BigQuery Geography support

### LINKED ISSUE #1882: BigQuery GEOGRAPHY type support
https://cloud.google.com/bigquery/docs/reference/standard-sql/data-types

GEOGRAPHY is a bit messy. There're various JSON/stringly representations so I'm tempted to map GEOGRAPHY to String in Scala but that means 1-to-2 mapping and we'll need some way to mark a String field (maybe annotation?) for @BigQueryType.toTable.
https://cloud.google.com/bigquery/docs/gis-data

### PR DESCRIPTION
**Pull request by anne-decusatis**
fixes #1882 

I made a wrapper case class instead of an annotation because I feel that keeping a 1:1 correspondence between Scala types and BQ types is worth the additional import on the user side if they work with geography types. I don't feel that strongly about this, let me know if you would like it changed. 

Before merge, I would like guidance on how to test this. I don't see any public datasets in BQ to write integration tests against with a GEOGRAPHY type - maybe I missed one? I can make a private dataset with an appropriate column but I'm not sure where is the best place to write a pipeline to test it against, and I couldn't find any good examples of test pipelines like that.  I don't think it should be merged as is, without testing that importing/exporting from BigQuery works in "real life" in addition to in the unit tests!

### CODE REVIEW

**Comment by anne-decusatis** [comment]
@nevillelyh I added a Geography field to ConverterProviderSpec. I didn't have to add any conversion of this type to ConverterProvider for the test to pass - I think it's being treated the same way a nested record of a case class containing a String would be treated. Does that need to be fixed?

**Comment by anne-decusatis** [comment]
test failure looks like: ```[info] Passed: Total 139, Failed 0, Errors 0, Passed 139
[error] (scio-bigquery / Test / test) sbt.TestsFailedException: Tests unsuccessful
[error] Total time: 613 s (10:13), completed Jul 30, 2019 3:27:41 PM
Exception in thread "Thread-43" java.lang.NoClassDefFoundError: org/apache/hadoop/util/ShutdownHookManager$2
	at org.apache.hadoop.util.ShutdownHookManager.getShutdownHooksInOrder(ShutdownHookManager.java:124)
	at org.apache.hadoop.util.ShutdownHookManager$1.run(ShutdownHookManager.java:52)
Caused by: java.lang.ClassNotFoundException: org.apache.hadoop.util.ShutdownHookManager$2
	at java.net.URLClassLoader.findClass(URLClassLoader.java:382)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 2 more
Exited with code 1``` and I don't see anything in the truncated log related to my change. should I rerun the tests?

**Comment by regadas** [comment]
@anne-decusatis that's a non issue ... but it's not the cause of test failure. It's misleading I know I'll fix it later.

**Comment by regadas** [comment]
@anne-decusatis what's the status on this? 😄

**Comment by anne-decusatis** [comment]
Hi @regadas , I wasn't working on this last week as I was on vacation. I'd like to do a test locally that it works with a GEOGRAPHY column in a BQ table and the data is transferred over the wire from BQ to Scio as I expect it to be (as a String). After that is working I'll remove the WIP from the title, and it'll be ready for review/merge :)

**Comment by sisidra** [comment]
Would it be possible to allow user to choose the format in which to convert data - GeoJSON, WKT or WKB?

**Comment by nevillelyh** [comment]
@sisidra with `case class Geography(wkt: String)` representation, we can defer that logic to user and avoid adding extra dependencies?

**Comment by nevillelyh** [comment]
@anne-decusatis what's the status of this? Ready to review/merge?

**Comment by anne-decusatis** [comment]
@nevillelyh I unfortunately haven't had a chance to prioritize the remaining work on this. I still would feel more confident before merge if I could run this branch against a BigQuery table that contained a GEOGRAPHY type and watch it successfully convert. I'd be fine with someone else picking that up so it isn't blocked on me - I don't expect to have time this week, not sure about the future.

**Comment by nevillelyh** [comment]
What should we do about this?

**Comment by regadas** [comment]
yeah, the work here seems to have stopped 😢 I would close this for now; @anne-decusatis can always reopen this once the work starts again.

**Comment by syodage** [comment]
@anne-decusatis would you mind if I start working on this? (I self-assigned, if you are working on please re-assigned it to you)

**Comment by syodage** [comment]
Changes moved to a different branch and rebased on lastest master.  created a new PR with new branch #2620

**Pull request closed without merging**
