### PR TITLE
Add infix to save methods

### PR DESCRIPTION
**Pull request by ravwojdyla**

### CODE REVIEW

**Comment by ravwojdyla** [comment]
Makes it more user friendly naming like `gs://<bucket>/data/path/part-0.protobuf.avro` etc

**Comment by nevillelyh** [comment]
LGTM but infix usually means infix notation though? Can you think of a better name?

**Comment by ravwojdyla** [comment]
infix comes from https://en.wikipedia.org/wiki/Infix. Options: `affix` `subsuffix` `innersuffix` or just `suffix`?

**Comment by nevillelyh** [comment]
Maybe just `suffix`? Same semantic as `.txt.deflate` where `.deflate` is added by the platform?

**Pull request merged**
