### PR TITLE
Bump beam to 0.6.0

### PR DESCRIPTION
**Pull request by ravwojdyla**

### CODE REVIEW

**Comment by nevillelyh** [comment]
Nothing broke? Like the first time ever?

**Comment by ravwojdyla** [comment]
@nevillelyh we will see - waiting for circleci.

**Comment by ravwojdyla** [comment]
And no - https://issues.apache.org/jira/browse/BEAM-1433. Will fix.

**Comment by ravwojdyla** [comment]
https://issues.apache.org/jira/browse/BEAM-1205 is also breaking, workaround [here](https://github.com/spotify/scio/pull/488/files#diff-86dcde70f730bb0f4605f71351fbcb1cR222).

**Comment by andrewsmartin** [comment]
👍

**Pull request merged**
