### PR TITLE
replace flatMap with nativeParDo, fix #820

### LINKED ISSUE #820: Unroll some inefficient flatMap we use internally
We sometimes do something like this:

```scala
val lhs: SCollection[String] = //...
val rhs: SCollection[String] = //...

val side = rhs.asListSideInput
lhs.withSideInputs(side)
  .flatMap { (x, s) =>
    s(side).map((x, _))
  }
```

This could be inefficient if `s(side): List[String]` is large since `.map` is eager. We should unroll this into a `DoFn`, loop over the side directly and call `ctx.output()`.

### PR DESCRIPTION
**Pull request by nevillelyh**

### CODE REVIEW

**Comment by nevillelyh** [comment]
Seems to improve joins slightly.

```
================================================================================
Benchmark           : Join
Extra arguments     : 
State               : DONE
Create time         : 2017-09-07T19:56:27.230411Z
Finish time         : 2017-09-07T20:01:31.474740Z
Elapsed             : 304 seconds
TotalMemoryUsage    : 12288094
TotalPdUsage        : 200001
TotalShuffleUsage   : 0
TotalSsdUsage       : 0
TotalVcpuTime       : 3200
================================================================================
Benchmark           : JoinShuffleService
Extra arguments     : --experiments=shuffle_mode=service
State               : DONE
Create time         : 2017-09-07T19:56:30.608903Z
Finish time         : 2017-09-07T20:01:17.363882Z
Elapsed             : 286 seconds
TotalMemoryUsage    : 11059268
TotalPdUsage        : 18000
TotalShuffleUsage   : 1667.0068038702552
TotalSsdUsage       : 0
TotalVcpuTime       : 2880
```

versus using Scio 0.4.0
```
================================================================================
Benchmark           : Join
Extra arguments     : 
State               : DONE
Create time         : 2017-09-07T18:47:35.439095Z
Finish time         : 2017-09-07T18:53:01.218100Z
Elapsed             : 325 seconds
TotalMemoryUsage    : 14131297
TotalPdUsage        : 230001
TotalShuffleUsage   : 0
TotalSsdUsage       : 0
TotalVcpuTime       : 3680
================================================================================
Benchmark           : JoinShuffleService
Extra arguments     : --experiments=shuffle_mode=service
State               : DONE
Create time         : 2017-09-07T18:47:37.986236Z
Finish time         : 2017-09-07T18:52:58.819166Z
Elapsed             : 320 seconds
TotalMemoryUsage    : 12902487
TotalPdUsage        : 21000
TotalShuffleUsage   : 1938.5306872851477
TotalSsdUsage       : 0
TotalVcpuTime       : 3360
================================================================================
```

**Comment by kanterov** [comment]
What is the sample size for the benchmark?

**Comment by nevillelyh** [comment]
LHS: 100M items, 10M keys, average 10 values per key
RHS: 50M items, 5M keys, average 10 values per key

**Comment by kanterov** [comment]
@nevillelyh I mean how much experiments did you do? We observe pretty high deviation in execution time for the same code on the same input.

**Comment by nevillelyh** [comment]
Yeah I should probably try a much bigger size but pretty sure this will improve performance since we've done similar hand tweaking before in joins.

**Comment by nevillelyh** [comment]
With 10x more elements, with `nativeParDo`:

```
================================================================================
Benchmark           : Join
Extra arguments     : 
State               : DONE
Create time         : 2017-09-07T20:51:38.484041Z
Finish time         : 2017-09-07T21:21:34.668696Z
Elapsed             : 1796 seconds
TotalMemoryUsage    : 103834361
TotalPdUsage        : 1690012
TotalShuffleUsage   : 0
TotalSsdUsage       : 0
TotalVcpuTime       : 27040
================================================================================
Benchmark           : JoinShuffleService
Extra arguments     : --experiments=shuffle_mode=service
State               : DONE
Create time         : 2017-09-07T20:51:41.551054Z
Finish time         : 2017-09-07T21:17:44.286403Z
Elapsed             : 1562 seconds
TotalMemoryUsage    : 89703407
TotalPdUsage        : 146001
TotalShuffleUsage   : 125276.84044528406
TotalSsdUsage       : 0
TotalVcpuTime       : 23360
```

Vs with `flatMap`:

```
================================================================================
Benchmark           : Join
Extra arguments     : 
State               : DONE
Create time         : 2017-09-07T20:54:09.117380Z
Finish time         : 2017-09-07T21:24:00.115869Z
Elapsed             : 1790 seconds
TotalMemoryUsage    : 103834374
TotalPdUsage        : 1690012
TotalShuffleUsage   : 0
TotalSsdUsage       : 0
TotalVcpuTime       : 27040
================================================================================
Benchmark           : JoinShuffleService
Extra arguments     : --experiments=shuffle_mode=service
State               : DONE
Create time         : 2017-09-07T20:54:11.909979Z
Finish time         : 2017-09-07T21:19:00.359356Z
Elapsed             : 1488 seconds
TotalMemoryUsage    : 84787935
TotalPdUsage        : 138001
TotalShuffleUsage   : 118498.05314170237
TotalSsdUsage       : 0
TotalVcpuTime       : 22080
```

Doesn't seem to make a huge difference.

**Comment by nevillelyh** [comment]
On second thought this might not be necessary since we're already using lazy instances of `TraversableOnce` e.g. `Iterator` in `flatMap`s. It only affects cases where you have a large eager collection as the result of `flatMap` but those are usually in user code and we don't want to expose this abstraction to the users. Will close for now.

**Pull request closed without merging**
