### PR TITLE
adding numMaxRecords and maxReadTime to use with DirectRunner

### PR DESCRIPTION
**Pull request by andrisnoko**
DirectRunner throws a NPE if numMaxRecords is not specified.

@nevillelyh @ravwojdyla @andrewsmartin

### CODE REVIEW

**Comment by nevillelyh** [comment]
LGTM but these 2 settings seem useful to `DirectRunner` only and creates bounded source instead of unbounded? Not sure if it's something we want to open up. Is this to allow users to test with real pubsub locally?

**Comment by andrisnoko** [comment]
@nevillelyh:  yeah this is for testing pubsub locally.

**Comment by nevillelyh** [comment]
I would prefer not to include these since they might make public API and common use cases confusing. Plus this is easily achievable with `sc.customInput()`. Should we add a note in FAQ instead?

**Comment by andrisnoko** [comment]
Yes, `sc.customInput()` should work for such cases, however, I ran into issues with it in scio 0.3

```scala
   sc.customInput(
      PubsubIO.Read
       .topic("projects/data-university/topics/data-university")
      .idLabel("id")
        .timestampLabel("ts")
        .withCoder(StringUtf8Coder.of()).maxNumRecords(50))```

**Comment by andrisnoko** [comment]
Thanks @nevillelyh, the name was missing from `sc.customInput()`. We really don't these changes. I will go ahead and close this PR.

```scala
sc.customInput("ReadFromPubsub",
      PubsubIO.read()
        .topic("projects/data-university/topics/data-university")
        .idLabel("id")
        .timestampLabel("ts")
        .withCoder(StringUtf8Coder.of()).maxNumRecords(50))
```

**Comment by nevillelyh** [comment]
Added a FAQ item here:
https://github.com/spotify/scio/wiki/FAQ#how-do-i-read-pubsub-input-in-a-local-pipeline

**Comment by vertexclique** [comment]
Currently, Since Beam API doesn't have those methods, this example doesn't work anymore.
Any alternative to achieve this?

**Pull request closed without merging**
