### PR TITLE
BigQueryValidationTest now

### PR DESCRIPTION
**Pull request by jbigred1**
This should address issues

### CODE REVIEW

**Comment by nevillelyh** [comment]
Failed with
```
[error] /home/circleci/scio/scio-test/src/test/scala/com/spotify/scio/bigquery/validation/SampleOverrideTypeProvider.scala:29:42: not found: type OverrideTypeProvider
[error] class SampleOverrideTypeProvider extends OverrideTypeProvider {
[error]                                          ^
```

**Comment by jbigred1** [comment]
this will fix https://github.com/spotify/scio/issues/1217 when merged

**Comment by nevillelyh** [comment]
Still not working for me in IntelliJ
WIP fix here: 6562d326aadcb1e94349c5350013d0005f31d332 but we need to check whether it's building in scio or end user's code base.

**Comment by jbigred1** [comment]
yeah this doesn't address the IntelliJ issues this is purely `sbt`

can solve the IntelliJ stuff when I'm back probably let me know if it's urgent and I can look into it

**Pull request merged**
